import 'dart:convert';
import 'dart:typed_data';
import 'package:cbor/cbor.dart';
import 'package:base45/base45.dart';
import 'package:crypto/crypto.dart';
import 'package:encrypt/encrypt.dart';

import 'config.dart';
import 'validation_result.dart';
import 'validation_error.dart';
import 'validation_rule.dart';

/// Main validator for secure QR codes.
///
/// Supports two payload formats simultaneously, to allow a staged
/// rollout without breaking QR codes already generated by app versions
/// currently in the store:
///
/// - **New format** (current generator): `Base45( IV + AES-CBC(CBOR(payload)) + HMAC[32] )`.
/// - **Legacy format** (pre-CBOR generator): `Base64( IV + AES-CBC(JSON(payload)) )`,
///   with the HMAC-SHA256 signature (hex string) embedded inside the JSON
///   payload before encryption, and timestamps in milliseconds.
///
/// The format is auto-detected from the payload's character set —
/// no version marker needed inside the QR code itself.
class SecureQRValidator {
  /// Validator configuration, shared by both the new and legacy decode
  /// paths. Must use the same secret key as the generator(s) that
  /// produced the QR codes being validated.
  final ValidatorConfig config;

  /// Business rules applied to the decoded data after all
  /// cryptographic and structural checks have passed, regardless of
  /// which payload format was used.
  final List<ValidationRule> _businessRules;

  /// AES decrypter instance (null if encryption is disabled). Shared
  /// by both decode paths, since both use AES-CBC with the same key.
  final Encrypter? _encrypter;

  /// Characters allowed by the Base45 alphabet (RFC 9285): digits,
  /// uppercase letters, space, and `$%*+-./:`. Used to distinguish the
  /// new format from legacy Base64 payloads, which in practice always
  /// contain lowercase letters and/or `=` padding (ciphertext has high
  /// enough entropy that a false match is not a realistic concern).
  static final RegExp _base45Alphabet = RegExp(r'^[0-9A-Z $%*+./:-]+$');

  /// Creates a new validator with the specified configuration and
  /// an optional list of business rules to apply to decoded data.
  SecureQRValidator(
      this.config, {
        List<ValidationRule> businessRules = const [],
      })  : _businessRules = businessRules,
        _encrypter = config.enableEncryption && config.secretKey != null
            ? Encrypter(AES(Key.fromUtf8(config.secretKey!.padRight(32))))
            : null;

  /// Validates a QR code payload and extracts its data if valid.
  ///
  /// Picks a decode path based on the payload's character set. If that
  /// path fails at a purely structural stage (encoding/decryption/
  /// format — as opposed to signature/expiration/business rule, which
  /// mean the structure was parsed correctly), retries with the other
  /// format as a safety net before giving up.
  ValidationResult validateQRPayload(String encodedPayload) {
    try {
      final triedNewFirst = _base45Alphabet.hasMatch(encodedPayload);
      final primary = triedNewFirst
          ? _validateNewFormat(encodedPayload)
          : _validateLegacyFormat(encodedPayload);

      if (_isStructuralFailure(primary)) {
        return triedNewFirst
            ? _validateLegacyFormat(encodedPayload)
            : _validateNewFormat(encodedPayload);
      }
      return primary;
    } catch (e) {
      return ValidationResult.invalid(ValidationError(
        type: ValidationErrorType.unknown,
        message: 'Unexpected error: ${e.toString()}',
      ));
    }
  }

  /// True if [result] failed before reaching semantic checks (signature,
  /// expiration, business rules), meaning the format detection heuristic
  /// may have picked the wrong decode path.
  bool _isStructuralFailure(ValidationResult result) {
    final type = result.error?.type;
    return type == ValidationErrorType.decoding ||
        type == ValidationErrorType.format ||
        type == ValidationErrorType.decryption;
  }

  // ---------------------------------------------------------------------
  // New format: Base45( IV + AES-CBC(CBOR(payload)) + HMAC[32] )
  // ---------------------------------------------------------------------

  /// Validates a payload produced by the current (CBOR/Base45) generator.
  ///
  /// Runs, in order: Base45 decoding, signature verification (on the
  /// still-encrypted body, so a forged/corrupted QR is rejected before
  /// paying the cost of decryption), decryption, CBOR decoding,
  /// version check, expiration check, then business rules.
  ValidationResult _validateNewFormat(String encodedPayload) {
    final Uint8List finalBytes;
    try {
      finalBytes = Uint8List.fromList(Base45.decode(encodedPayload));
    } catch (e) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.decoding,
        message: 'Invalid Base45 encoding',
      ));
    }

    Uint8List body = finalBytes;
    if (config.enableSignature) {
      if (config.secretKey == null || finalBytes.length < 32) {
        return ValidationResult.invalid(const ValidationError(
          type: ValidationErrorType.signature,
          message: 'Payload too short to contain a signature',
        ));
      }
      final splitIndex = finalBytes.length - 32;
      body = finalBytes.sublist(0, splitIndex);
      final receivedTag = finalBytes.sublist(splitIndex);
      final expectedTag = _hmac(body);
      if (!_constantTimeEquals(receivedTag, expectedTag)) {
        return ValidationResult.invalid(const ValidationError(
          type: ValidationErrorType.signature,
          message: 'Invalid signature',
        ));
      }
    }

    final Uint8List plainBytes;
    if (config.enableEncryption && _encrypter != null) {
      try {
        if (body.length < 16) throw const FormatException('body too short');
        final iv = IV(Uint8List.fromList(body.sublist(0, 16)));
        final cipherBytes = Uint8List.fromList(body.sublist(16));
        plainBytes = Uint8List.fromList(
          _encrypter!.decryptBytes(Encrypted(cipherBytes), iv: iv),
        );
      } catch (e) {
        return ValidationResult.invalid(const ValidationError(
          type: ValidationErrorType.decryption,
          message: 'Decryption failed',
        ));
      }
    } else {
      plainBytes = body;
    }

    final CborValue decoded;
    try {
      decoded = cbor.decode(plainBytes);
    } catch (e) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.format,
        message: 'Invalid CBOR payload',
      ));
    }

    if (decoded is! CborMap) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.format,
        message: 'Unexpected payload structure',
      ));
    }

    final idValue = decoded[const CborSmallInt(0)];
    final tsValue = decoded[const CborSmallInt(1)];
    final versionValue = decoded[const CborSmallInt(2)];
    final dataValue = decoded[const CborSmallInt(3)];

    if (idValue is! CborBytes ||
        tsValue is! CborSmallInt ||
        versionValue is! CborSmallInt ||
        dataValue == null) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.format,
        message: 'Missing or invalid payload fields',
      ));
    }

    final idBytes = Uint8List.fromList(idValue.bytes);
    final tsSeconds = tsValue.toInt();
    final version = versionValue.toInt();
    final data = _fromCbor(dataValue);

    if (data is! Map<String, dynamic>) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.format,
        message: 'The data field is invalid',
      ));
    }

    if (version > config.maxSupportedVersion) {
      return ValidationResult.invalid(ValidationError(
        type: ValidationErrorType.version,
        message: 'Unsupported version: $version',
      ));
    }

    final generatedAt = DateTime.fromMillisecondsSinceEpoch(tsSeconds * 1000);
    final id = _bytesToHex(idBytes);

    return _finalizeResult(data: data, generatedAt: generatedAt, id: id);
  }

  // ---------------------------------------------------------------------
  // Legacy format: Base64( IV + AES-CBC(JSON(payload)) )
  // Kept for QR codes generated by app versions predating the CBOR/Base45
  // migration, still in circulation while the store rollout completes.
  // TODO: remove once telemetry shows no legacy-format scans remain.
  // ---------------------------------------------------------------------

  /// Validates a payload produced by the pre-CBOR generator: signature
  /// embedded (as hex) inside the JSON before encryption, timestamps in
  /// milliseconds, everything Base64-encoded rather than Base45.
  ValidationResult _validateLegacyFormat(String encodedPayload) {
    final jsonPayload = _decryptOrDecodeLegacy(encodedPayload);
    if (jsonPayload == null) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.decryption,
        message: 'Decryption or decoding failed',
      ));
    }

    final payload = _parseLegacyPayload(jsonPayload);
    if (payload == null) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.format,
        message: 'Invalid payload format',
      ));
    }

    final version = payload['version'] as int;
    if (version > config.maxSupportedVersion) {
      return ValidationResult.invalid(ValidationError(
        type: ValidationErrorType.version,
        message: 'Unsupported version: $version',
      ));
    }

    if (config.enableSignature && !_verifySignatureLegacy(payload)) {
      return ValidationResult.invalid(const ValidationError(
        type: ValidationErrorType.signature,
        message: 'Invalid signature',
      ));
    }

    final generatedAt =
    DateTime.fromMillisecondsSinceEpoch(payload['timestamp'] as int);
    final data = payload['data'] as Map<String, dynamic>;
    final id = payload['id'] as String;

    return _finalizeResult(data: data, generatedAt: generatedAt, id: id);
  }

  /// Legacy counterpart of the new format's decryption step: base64
  /// decode, then AES-CBC decrypt (IV = first 16 bytes) straight to a
  /// JSON string, or plain base64+utf8 decode when encryption is off.
  String? _decryptOrDecodeLegacy(String encodedPayload) {
    try {
      if (config.enableEncryption && _encrypter != null) {
        final bytes = base64Decode(encodedPayload);
        final iv = IV(bytes.sublist(0, 16));
        final encryptedBytes = bytes.sublist(16);
        return _encrypter!.decrypt(Encrypted(encryptedBytes), iv: iv);
      } else {
        return utf8.decode(base64Decode(encodedPayload));
      }
    } catch (e) {
      return null;
    }
  }

  /// Parses and structurally validates a decrypted legacy JSON payload.
  Map<String, dynamic>? _parseLegacyPayload(String jsonPayload) {
    try {
      final payload = jsonDecode(jsonPayload);
      if (payload is! Map<String, dynamic>) return null;

      final requiredFields = ['data', 'timestamp', 'version', 'id'];
      if (!requiredFields.every(payload.containsKey)) return null;

      if (payload['data'] is! Map<String, dynamic>) return null;
      if (payload['timestamp'] is! int) return null;
      if (payload['version'] is! int) return null;
      if (payload['id'] is! String) return null;

      return payload;
    } catch (e) {
      return null;
    }
  }

  /// Verifies the legacy signature: HMAC-SHA256 (hex string) computed
  /// over the JSON payload *without* the signature field, on the
  /// already-decrypted plaintext (sign-then-encrypt — the order used by
  /// the pre-CBOR generator, opposite to the new format's
  /// encrypt-then-MAC).
  bool _verifySignatureLegacy(Map<String, dynamic> payload) {
    if (!config.enableSignature || config.secretKey == null) return true;

    final originalSignature = payload.remove('signature');
    if (originalSignature == null) return false;

    final calculatedSignature = _generateLegacySignature(payload);
    return originalSignature == calculatedSignature;
  }

  /// Computes the legacy hex-encoded HMAC-SHA256 signature over a JSON
  /// payload map (used only by the legacy decode path).
  String _generateLegacySignature(Map<String, dynamic> payload) {
    final data = jsonEncode(payload);
    final key = utf8.encode(config.secretKey!);
    final bytes = utf8.encode(data);
    final hmac = Hmac(sha256, key);
    return hmac.convert(bytes).toString();
  }

  // ---------------------------------------------------------------------
  // Shared logic (format-independent)
  // ---------------------------------------------------------------------

  /// Applies expiration check and business rules, common to both decode
  /// paths, once [data], [generatedAt] and [id] have been extracted.
  ValidationResult _finalizeResult({
    required Map<String, dynamic> data,
    required DateTime generatedAt,
    required String id,
  }) {
    if (config.enableExpirationCheck && _isExpired(generatedAt)) {
      return ValidationResult.expiredWithData(
        error: const ValidationError(
          type: ValidationErrorType.expired,
          message: 'QR code expired',
        ),
        data: data,
        generatedAt: generatedAt,
        id: id,
      );
    }

    final businessError = _applyBusinessRules(data);
    if (businessError != null) {
      return ValidationResult.invalid(businessError);
    }

    return ValidationResult.valid(data: data, generatedAt: generatedAt, id: id);
  }

  /// Computes an HMAC-SHA256 tag (32 raw bytes) over [body], using the
  /// configured secret key. Used by the new format only (the legacy
  /// format uses [_generateLegacySignature] instead).
  Uint8List _hmac(List<int> body) {
    final hmac = Hmac(sha256, utf8.encode(config.secretKey!));
    return Uint8List.fromList(hmac.convert(body).bytes);
  }

  /// Compares two byte sequences in constant time, to avoid leaking
  /// information about the expected tag through response-time
  /// differences (timing attack mitigation).
  bool _constantTimeEquals(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    var result = 0;
    for (var i = 0; i < a.length; i++) {
      result |= a[i] ^ b[i];
    }
    return result == 0;
  }

  /// Converts raw id bytes back into a lowercase hex string (new format
  /// only — the legacy format already carries its id as a string).
  String _bytesToHex(Uint8List b) =>
      b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

  /// Recursively converts a decoded [CborValue] tree back into plain
  /// Dart objects (Map, List, String, int, double, bool, null).
  /// Used by the new format only.
  dynamic _fromCbor(CborValue v) {
    if (v is CborMap) {
      return {
        for (final e in v.entries) _fromCbor(e.key).toString(): _fromCbor(e.value),
      };
    }
    if (v is CborList) return v.map(_fromCbor).toList();
    if (v is CborSmallInt) return v.toInt();
    if (v is CborFloat) return v.value;
    if (v is CborBool) return v.value;
    if (v is CborString) return v.toString();
    if (v is CborNull) return null;
    return null;
  }

  /// Checks if a QR code generated at [generatedAt] has exceeded the
  /// configured validity duration. Shared by both decode paths.
  bool _isExpired(DateTime generatedAt) {
    return DateTime.now().difference(generatedAt) > config.validityDuration;
  }

  /// Runs all configured business rules against [data] and returns
  /// the first validation error encountered, or null if all rules pass.
  /// Shared by both decode paths.
  ValidationError? _applyBusinessRules(Map<String, dynamic> data) {
    for (final rule in _businessRules) {
      final error = rule(data);
      if (error != null) {
        return ValidationError(type: ValidationErrorType.businessRule, message: error);
      }
    }
    return null;
  }
}
